import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "./components/Navbar";
import Provider from "./components/Provider";
import Footer from "./components/Footer";

const customFont = localFont({
  src: "../public/fonts/Virgil.ttf",
  variable: "--font-secondary",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`container ${inter.className} ${customFont.variable} grid grid-rows-[1fr_auto] min-h-screen antialiased`}
      >
        <Provider>
          <Navbar />
          <main className="mt-16">{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
